### ISSUE TITLE
Performance concern

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-header-footer#1]
Release of new nav (in its previous incarnation of next-header + next-navigation + next-footer) seems to coincide with this big drop in performance

article
![image](https://cloud.githubusercontent.com/assets/447559/7883161/33730eca-060c-11e5-8101-86a1f2783521.png)

front
![image](https://cloud.githubusercontent.com/assets/447559/7883187/6bc5aefe-060c-11e5-8465-395bfc2e5804.png)

**Comment by i-like-robots** [comment]
What's this measure; time to first byte?

**Comment by wheresrhys** [comment]
It's time to render from here http://ft-next-graphite-dashboard.herokuapp.com/performance which... err... I don't know exactly what that is

**Comment by ironsidevsquincy** [comment]
it's wpt's definition of render, I'm guessing, which I can never remember

**Comment by i-like-robots** [comment]
The only difference is that we went from a static HTML template to generating the HTML dynamically (a simple loop). Can Handlebars really be that slow?

**Comment by aintgoin2goa** [comment]
Is this still an issue?  that link goes to a page that doesn't seem to show any graphs...

**Comment by wheresrhys** [comment]
I doubt it
