### ISSUE TITLE
Search field does not display clear field (x) button in Firefox or Safari

### ISSUE THREAD

**Issue by andygout** [Financial-Times/n-header-footer#117]
Chrome:
![chrome](https://cloud.githubusercontent.com/assets/10484515/10797005/85c3fd02-7d98-11e5-94eb-6a10eb53fe76.png)

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/10484515/10797046/b0d9eeb6-7d98-11e5-867d-8031bad6fba7.png)

Safari:
![safari](https://cloud.githubusercontent.com/assets/10484515/10797007/8ba2ddec-7d98-11e5-9226-de6cbe8db7a1.png)

**Comment by ironsidevsquincy** [comment]
Think that's a thing done by the browser itself, i.e. only by Chrome

**Comment by andygout** [comment]
Ah, right you are.  It is default for IE as well.
