### ISSUE TITLE
a11y improvements

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-header-footer#13]
- [x] Addition of `role="navigation"` and  `aria-label="Main navigation"` required.
- [x] Add `role="search"` to search form
- [x] Label required for search box (can be visually hidden). Placeholder text of 'search' is not a useful placeholder.
- [ ] Discuss/test appropriate role and labelling for primary tools
- [x] `title="Go to homepage"` nice to have on logo link
- [x] `<abbr>` elements require text content ([here](https://github.com/Financial-Times/n-header-footer/blob/ddffa2efdee3a8ce5dc74b6fa33b4da60fec5591/templates/partials/primary-tools.html#L9))

**Comment by adamsilver** [comment]
Moved "Discuss/test appropriate role and labelling for primary tools" to separate issue.  Rest are completed.
