### ISSUE TITLE
CSS smells

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-header-footer#147]
The CSS in this repo has a lot of smells. We have nesting, confused class names, redundant properties and a mix of old header code and new header code that makes everything hard to read.

BEM MIA:

- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_primary-tools.scss#L101
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_navigation.scss#L231
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_navigation.scss#L300-L301
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_navigation.scss#L334
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_navigation.scss#L382

There are many cases of redundant properties being declared:

- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_base.scss#L12-L14
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_base.scss#L66-L71 (what is this?)
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_masthead.scss#L35
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_masthead.scss#L57
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_masthead.scss#L63
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_navigation.scss#L19
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_navigation.scss#L138
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_navigation.scss#L152-L155
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_navigation.scss#L199
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_navigation.scss#L207 (As opposed to what?)
- https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_navigation.scss#L294 

This block is nearly incomprehensible =[ :

https://github.com/Financial-Times/n-header-footer/blob/master/src/scss/header/_navigation.scss#L297-L387

**Comment by ironsidevsquincy** [comment]
The whole thing is incomprehensible and would advise, for your sanity, to not look at it

Basically, whoever comes round to building the new version of the header/nav should completely start from scratch
