### ISSUE TITLE
Decouple the footer and next-welcome

### ISSUE THREAD

**Issue by ironsidevsquincy** [Financial-Times/n-header-footer#275]
There seems to be some indirect link between the footer and [welcome-message](https://github.com/Financial-Times/n-ui/tree/master/welcome-message), i.e. you always need to include both to get either to work

It would be great to decouple this, i.e. some apps just want the footer without the welcome message

@aintgoin2goa, @i-like-robots, @andygout

**Comment by i-like-robots** [comment]
Fixed in n-ui
