### ISSUE TITLE
Tracking Attributes

### ISSUE THREAD

**Issue by aintgoin2goa** [Financial-Times/n-header-footer#279]
Smarten up our tracking attribute names as discussed with Adam

**Comment by aintgoin2goa** [comment]
https://github.com/Financial-Times/n-navigation/issues/92

**Comment by adambraimbridge** [comment]
Thanks. Happy to discuss any time.

**Comment by i-like-robots** [comment]
this has been discussed and amended within n-ui implementation of new o-header
