### ISSUE TITLE
Logo should not be an H1

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-header-footer#39]
Logos should be an image and not marked up as a heading. Keep the top level heading for the main page content (no browser yet implements the specced document outline w/ multiple headers that I know of). The document title is fine for naming the source of the document and orientating a user.

```html
<a href="..." title="Go to homepage">
  <img src="..." srcset="..." rel="logo" alt="Financial Times">
</a>
```

https://github.com/Financial-Times/n-header-footer/blob/master/templates/header.html#L17-L21

Some more reasoning:
- http://csswizardry.com/2010/10/your-logo-is-an-image-not-a-h1/
- http://www.amberweinberg.com/the-logo-to-h1-or-not-to-h1/

CC @charypar

**Comment by charypar** [comment]
Hmmm... Isn't html5 supposed to support a h1 per section level? In which case "Financial Times" is arguably _the_ headline of the entire page (maybe except the article page...?). I can definitely see your point though, this part of the markup needs some more thinking. Making it an image is way to visual for my taste though, there should be a semantic representation of a title, although you're probably right the content of `<title>` is probably enough...

Do you have any thoughts on what to use as a guide for picking the right markup option? Some kind of practical outcomes you get for the different options, like screen reader behaviour, constructed document outline, things like that... I don't love the idea of guiding the markup by "opinion on some css blog" :)

**Comment by i-like-robots** [comment]
HTML5 does spec this but nothing actually implements this outline algorithm yet that I'm aware of - the consensus in a11y circles seems to be that no screen reader supports it yet either. Or as Steve Faulkner put it:

> The HTML5 Document Outline is a concept that lives in the HTML specification, but is essentially a fiction in the real world.

For actual markup this is what the HTML5 spec uses:

```html
<p>
  <a href="http://www.w3.org/">
    <img alt="W3C" height="48" src="http://www.w3.org/Icons/w3c_home" width="72">
  </a>
</p>
```

And this is the ARIA spec:

```html
<div class="head" role="complementary" aria-labelledby="title">
  <a href="http://www.w3.org/">
    <img alt="W3C" height="48" src="http://www.w3.org/Icons/w3c_home" width="72">
  </a>
  <h1 id="title">
    Accessible Rich Internet Applications (<abbr title="Accessible Rich Internet Applications">WAI-ARIA</abbr>) 1.0
  </h1>
  ...
</div>
```

I quite like the second option. We could visually hide the title. On the homepage (where there is usually no clear top-level heading) we could mark it up as an H1, elsewhere just a paragraph. What do you think?

**Comment by michaelandrew** [comment]
We actually follow the same principles as Harry Roberts and use the base64 1px transparent png, then style it using CSS. Mainly because we use different logos on different screen sizes.

    <a class="identity" ui-sref="home">
    <img class="identity__img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Vizibl logo" />

**Comment by i-like-robots** [comment]
@michaelandrew Do you think you'll consider updating your implementation to use `srcset` and `sizes` in the future?

**Comment by michaelandrew** [comment]
@i-like-robots 100%. We are already in talks to completely get rid of sprites and any sort of icon png as it is with a look towards vectoring, however `srcset` and `sizes` may not be an option for us at the moment without polyfills as we have to support IE9.

**Comment by charypar** [comment]
@i-like-robots I like the ARIA option, we could pretty much put the `h1` in next-front-page and not have it in the masthead at all.

**Comment by i-like-robots** [comment]
@charypar :+1:
