### ISSUE TITLE
Ability to scroll content behind menu on mobile

### ISSUE THREAD

**Issue by aRhombus** [Financial-Times/n-header-footer#49]
When nav menu is engaged on mobile, you can still scroll the content. If scrolling down, it momentarily causes the menu to shift and the header to disappear.

**Comment by charypar** [comment]
This seems to be related to #66. After fixing it I can no longer reproduce it. Leaving open for re-testing.

**Comment by aRhombus** [comment]
Re-tested. Can't reproduce issue, but should be monitored once in the wild. Closing for now.
