### ISSUE TITLE
Header and News/FastFt should be integrated

### ISSUE THREAD

**Issue by aRhombus** [Financial-Times/n-header-footer#58]
They're currently stylistically different on mobile ie. News and FastFt fonts as large as the Financial Times. No current indication of hierarchy.

**Comment by charypar** [comment]
What's the action to resolve, is there a design?

**Comment by aRhombus** [comment]
Mainly font sizes, height of entire area vs header. Selected state should be bold. "NEWS" all caps. Refer to wireframe for reference and let me know if you need any additional info.
