### ISSUE TITLE
Search Box Style - lines need to be cleaned up

### ISSUE THREAD

**Issue by aRhombus** [Financial-Times/n-header-footer#63]
![search-style](https://cloud.githubusercontent.com/assets/6070114/9790410/d07801e0-57cd-11e5-9bd2-b3d9d2c71216.png)

**Comment by aRhombus** [comment]
Reopening as the lines are still there on all devices. This is a visual design decision, necessarily a QA blocker.

**Comment by charypar** [comment]
cam we make that a separate one? this was about clearly buggy rendering, now it should be doing what the design said. Correct me if I'm wrong.

**Comment by aRhombus** [comment]
I can make a separate one, but the title was: " Search Box Style - lines
need to be cleaned up", screenshots show the lines.

So maybe the buggy rendering is a separate issue that's now resolved?

On 17 September 2015 at 15:30, Viktor Charypar <notifications@github.com>
wrote:

> cam we make that a separate one? this was about clearly buggy rendering,
> now it should be doing what the design said. Correct me if I'm wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/n-header-footer/issues/63#issuecomment-141104586>
> .
>



-- 

*Austin Keeble*


*Red Badger Consulting Limited*12 Mallow Street, London EC1Y 8RQ  UK
*W *http://red-badger.com
*T *@redbadgerteam <http://twitter.com/redbadgerteam>

Registered in England No. 7242017
Registered Office: York Cottage, The Green, Pirbright, Woking, Surrey GU24
0JT

**Comment by charypar** [comment]
Oh in that case it was a misunderstanding of the issue!

**Comment by aRhombus** [comment]
Indeed! Soz. In essence, you already fixed buggy rendering. Reopened style
issue covers the line stuff, so we're all good, yah? Not necessarily a QA
blocker, bill defer to Clem on this.

On 17 September 2015 at 15:39, Viktor Charypar <notifications@github.com>
wrote:

> Oh in that case it was a misunderstanding of the issue!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/n-header-footer/issues/63#issuecomment-141107000>
> .
>



-- 

*Austin Keeble*


*Red Badger Consulting Limited*12 Mallow Street, London EC1Y 8RQ  UK
*W *http://red-badger.com
*T *@redbadgerteam <http://twitter.com/redbadgerteam>

Registered in England No. 7242017
Registered Office: York Cottage, The Green, Pirbright, Woking, Surrey GU24
0JT

**Comment by charypar** [comment]
Lines were removed in e1f7ae6.
