### ISSUE TITLE
o-grid v4 and v4-beta differences in masthead

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-header-footer#80]
v4 beta (homepage)
<img width="425" alt="screen shot 2015-09-25 at 16 58 10" src="https://cloud.githubusercontent.com/assets/271645/10105460/ae5d6674-63a6-11e5-9681-067aa6b33392.png">

v4 (article page)
<img width="423" alt="screen shot 2015-09-25 at 16 58 28" src="https://cloud.githubusercontent.com/assets/271645/10105461/ae618fce-63a6-11e5-98e2-d904fbe4b5d3.png">

**Comment by charypar** [comment]
Container and row classes need to shift around a little bit to get the alignment right and the gutters symmetrical. There is also an extra `padding: 0` somewhere and extra right padding on the menu icon.
