### ISSUE TITLE
Most toggling doesn't work in Chrome (and possibly others) on iOS 9

### ISSUE THREAD

**Issue by charypar** [Financial-Times/n-header-footer#82]
This is a [known issue](https://code.google.com/p/chromium/issues/detail?id=534210) in iOS 9 which breaks the general sibling selector (which the nav uses for interaction) in `UIWebView` - the rendering engines all browsers **but Safari** use on iOS. Safari's `WKWebView` seems ok.

This means the issue affects everyone on iOS 9 _not_ using Safari. Presumably Apple will fix the bug in a future update for iOS, as it's a fairly high profile issue.

There is a way to work around it we can try (using adjacent sibling selector instead of the general one), but it requires some changes to the navigation's markup which may cause other issues, i.e. the workaround isn't completely straightforward.

**Comment by charypar** [comment]
Upgraded to QA blocker after discussing with Gadi - can't wait for Apple to fix things (and it seems the problem is [also present in WebKit on Android](http://freshinbox.com/blog/android-css-general-sibling-selector-bug/))

**Comment by tgabe** [comment]
Looks good. Tested alongside https://github.com/Financial-Times/next-front-page/issues/327.
